[system]
addr = "0.0.0.0:5000"
mode = "debug"
username = "cargoboat"
password = "cargoboat"
[postgres]
address = "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=cargoboat sslmode=disable"
log = true
max_open = 100
max_idle = 10